list=["sunday","monday","tuesday","wednesday","thuesday","friday","saturday"]
y=iter(list)
print(next(y))
print(next(y))
a=input("enter your name")
print(next(y))
print(next(y))
print(next(y))
b=input("enter your name")
print(next(y))
print(next(y))